### PR TITLE
Add relative diffusivity example

### PR DESCRIPTION
**Pull request by TomTranter**

### CODE REVIEW

**Comment by TomTranter** [comment]
@jgostick build failing for a number of reasons - One is a silly unexpected printed message which should be a logger message. Other fails are because I think objects from other scripts are hanging around in memory and we're getting name conflicts

**Comment by jgostick** [comment]
I think the print out statements you are referring to are coming from the OP algorithm?  Where ever they are, we would have to update them on OpenPNM, then push the changes to PyPI so that this repo will get them when it runs ``pip install openpnm`` during the travis testing.  I wonder if we should use the ``pip install http://github.com/PMEAL/OpenPNM/master`` approach to install from the latest source?  I'm going to open this as an issue.

**Comment by TomTranter** [comment]
OK I've made a PR (Tiny bug fixes #544) which addresses this print message issue and also a few other small things. I think if we can change the source this examples directory looks at to be the latest master branch it would be easier in the short term but probably going forward the documentation should keep step with the pypi code. If we want to make major changes to the code and reflect that in the docs we should branch the docs.

**Comment by jgostick** [comment]
I have just tagged a version 1.4.6 on Github and deployed it to PyPI so running the tests should use the new version and hence pass.

**Pull request merged**
