### PR TITLE
Issue #5 Examples - added thermal conduction example

### PR DESCRIPTION
**Pull request by MichaelHoeh**
As discussed, added a thermal conduction example based on the test in OpenPNM

### CODE REVIEW

**Comment by jgostick** [comment]
The example is failing.  There is an annoying 'gotcha' in the MD syntax.  You have to include a blank line at the end of each code block before the closing ``` marks.  I tried to update myself, but I can't work on it since it's actually a PR from michael's own fork.

**Comment by MichaelHoeh** [comment]
Thanks for the hint Jeff. I introduced the blank lines and committed again, now Travis completes the committed example successfully. I also had to remove the plotting code block, I now put it as inline code, as Travis kept failing on the plotting commands. I don't know why that is, but I saw that all other examples had no plotting code block either, so I removed it here as well.

**Comment by MichaelHoeh** [comment]
I just noticed that still Travis complains that build failed, yet that is not due to this example, but rather due to the file IO_and_Visualization/Statoil_import.md, which fails on the "assert op.__version__ == '1.4.0'". So this example should be ready to be merged, the Travis failure is outside this example.

**Comment by jgostick** [comment]
Interesting!! I updated PyPI last night to version 1.4.5.  I don't remember
adding this assert, but I think it should be removed. I'll do it asap.

**Comment by jgostick** [comment]
Ok, remerge the master onto your branch to get the changes I made to the statoil file, then commit to have travis re-run the tests.

**Comment by mohammadamin-sadeghi** [comment]
I think the error contour at the end of this example should be removed. The whole point of this is to show how accurate the model is, and contour plots are not good at showing this. One has to go through the legend and gradually finds out that the error is too small. Instead, I suggest plotting the temperature profile at different horizontal cutlines accompanied by some data points from the analytical solution. This way, the reader will right away get the impression that the model and the analytical solution agree. @MichaelHoeh @jgostick

**Pull request merged**
